#### Numpy To store all types of data sets (1D, 2D,3D arrays, etc.) - uses Fixed type

In [1]:
## importing numpy library
import numpy as np

In [6]:
## initializing an array
a = np.array([1,2,3])
print(a)

print("-" *30)

b = np.array([[1.00,3.56,7.23],[5.77,5.89,4.77]])
print(b)

c = np.array([1.00,3.56,7.23],[5.77,5.89,4.77])    ##wrote two separate lists as separate arguments, which is invalid. wrap them in an outer list [...]
print(c)

[1 2 3]
------------------------------
[[1.   3.56 7.23]
 [5.77 5.89 4.77]]


TypeError: Field elements must be 2- or 3-tuples, got '5.77'

In [9]:
## How to get the number of dimensions?

print(a.ndim)
print(b.ndim)

1
2


In [10]:
## Get Shape
a.shape
b.shape             ## use print() , to get shape of a and b

print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [11]:
## Get type
print(a.dtype)
print(b.dtype)

int64
float64


In [15]:
## Get Size
a = np.array([1,2,3] , dtype = "int16")
print(a.itemsize)
print(a.size)
print(a.nbytes)

print("-" * 30)

b = np.array([1,2,3] , dtype = "int32")
print(b.itemsize)
print(b.size)
print(b.nbytes)

2
3
6
------------------------------
4
3
12


#### Accessing/changing specific elements, rows, columns, etc

In [19]:
a = np.array([[2,3,4,5,6,7,5] , [3,6,5,4,7,9,7]])
print(a)

[[2 3 4 5 6 7 5]
 [3 6 5 4 7 9 7]]


In [22]:
# Get specific elements - [row, column]
print(a[1,5])
print(a[1,-4])    #negative indexing

9
4


In [25]:
# Get specific rows 
print(a[0,:]) 
print(a[1,:]) 

# Get specific columns
print(a[:,2]) 
print(a[:,5]) 

# using [starting index:end index:step index] - get from 1st list, values 1 to 7 with step 6
print(a[0,1:6:2])
print(a[0,1:-1:2])


[2 3 4 5 6 7 5]
[3 6 5 4 7 9 7]
[4 5]
[7 9]
[3 5 7]
[3 5 7]


In [28]:
# change
a = np.array([[2,3,4,5,6,7,5] , [3,6,5,4,7,9,7]])
print(a)

a[0,2] = 25     #change row 0, column 2
print(a)

a[:,2] =[1,2]   # change all rows (:) in column 2
print(a)

[[2 3 4 5 6 7 5]
 [3 6 5 4 7 9 7]]
[[ 2  3 25  5  6  7  5]
 [ 3  6  5  4  7  9  7]]
[[2 3 1 5 6 7 5]
 [3 6 2 4 7 9 7]]


In [ ]:
*3-D example

In [46]:
b = np.array([[[5,8] , [4,3]] , [[6,5] ,[7,9]]])
print(b)

[[[5 8]
  [4 3]]

 [[6 5]
  [7 9]]]


In [50]:
# Get specific elements - [row, column]
print(b[0,0,1])   ##select the first block->select the first row inside that block->select the second element
print(b[1,1,1])

print(b[:,1,1])  ##take all blocks (block 0 & block 1)->take the second row in each block->take the second element in that row
print(b[1,1,:])
print(b[:,1,:])

# change or replace
b[:,1,:] = [[10,15],[18,18]] ##take all blocks (block 0 & block 1)->take the second row in each block->take all elements of that row
b


8
18
[15 18]
[18 18]
[[10 15]
 [18 18]]


array([[[ 5,  8],
        [10, 15]],

       [[ 6,  5],
        [18, 18]]])

*Day 2 - Intializing data types of array

In [9]:
##All 0s matrix
import numpy as np

a = np.zeros((2,3))    ## create 2 rows , 3 columns
print(a)

print("-" *30)

b = np.zeros((2,3,3))  # create 3D array
print(b)

[[0. 0. 0.]
 [0. 0. 0.]]
------------------------------
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


In [10]:
##All 1s matrix
a = np.ones((2,3), dtype = "int32")    ## create 2 rows , 3 columns
print(a)

print("-" *30)

b = np.ones((2,3,3), dtype = "float64")
print(b)

[[1 1 1]
 [1 1 1]]
------------------------------
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


In [13]:
##Any other number
np.full((3,3),240)                                ##np.full((shape),(value))

print("-" *30)

a = np.array([[2,3,4,5,6,7,5] , [3,6,5,4,7,9,7]])
print(a)
print(np.full_like(a,4))
print(np.full(a.shape,4))


------------------------------
[[2 3 4 5 6 7 5]
 [3 6 5 4 7 9 7]]
[[4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4]]
[[4 4 4 4 4 4 4]
 [4 4 4 4 4 4 4]]


In [19]:
##create Random numbers - decimal and integers
d = np.random.rand(4,2)
print(d)

print("-" *30)

b = np.random.rand(2,2,3)
print(b)

print("-" *30)

a = np.array([[2,3,4,5,6,7,5] , [3,6,5,4,7,9,7]])
print(np.random.random_sample(a.shape))

print("-" *30)

e = np.random.randint(7, size= (2,3))   ##generates random integers from 0 up to 6 (since 7 is exclusive) then creates a 2×3 array.
print(e)

print("-" *30)

e = np.random.randint(4,7, size= (2,3))   ##generates random integers from 4 to 7
print(e)

[[0.66418698 0.34331411]
 [0.40809955 0.72431008]
 [0.02625157 0.15081037]
 [0.78634032 0.25092976]]
------------------------------
[[[0.09079349 0.21895721 0.19178206]
  [0.54139254 0.27137302 0.25829653]]

 [[0.90500556 0.83412888 0.5649335 ]
  [0.36394351 0.85575103 0.82046242]]]
------------------------------
[[0.5406676  0.02153991 0.09317087 0.71943742 0.33685553 0.04703255
  0.69334387]
 [0.16625893 0.35563315 0.22268017 0.29523566 0.91581255 0.06427424
  0.69098393]]
------------------------------
[[3 4 5]
 [2 5 4]]
------------------------------
[[4 6 5]
 [6 6 5]]


In [20]:
##Identity matrix
print(np.identity(5))
print(np.identity(3))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [25]:
##Repeat the arrays
a = np.array([1,2,3])
r = np.repeat(a,3)         ##a is repeated 3 times (since no axis, it flattens).
print(r)

a = np.array([[1,2,3]])
r = np.repeat(a,3 , axis = 0)   ##row 3 times (axis=0 - row direction).
print(r)

a = np.array([[1,2,3]])
r = np.repeat(a,3 , axis = 1)  ##Repeats each element along the columns (axis=1 - column direction).
print(r)

[1 1 1 2 2 2 3 3 3]
[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1 1 1 2 2 2 3 3 3]]


In [29]:
##copying
a = np.array([1,2,3])
b = a
b[0] = 100
print(b)
print(a)

print("-" * 30)

a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(b)
print(a)

[100   2   3]
[100   2   3]
------------------------------
[100   2   3]
[1 2 3]


#### Mathematics operations

In [30]:
a = np.array([1,4,8,6])
print(a + 2)            ##add 2 to each elements in a 
print(a - 2)
print(a * 2)
print(a ** 2)
print(a / 2)

[ 3  6 10  8]
[-1  2  6  4]
[ 2  8 16 12]
[ 1 16 64 36]
[0.5 2.  4.  3. ]


In [42]:
a = np.array([[1,4,8,6],[5,6,7,9]])
b = np.array([[5,8,10,12],[7,9,5,0]])

print(a + b)   #[1+5, 4+8, 8+10, 6+12] - [6, 12, 18, 18]    [5+7, 6+9, 7+5, 9+0] - [12, 15, 12,  9]

print(a * b)  #[1*5, 4*8,  8*10, 6*12] - [5, 32, 80, 72]    [5*7, 6*9,  7*5,  9*0]  - [35, 54, 35,  0]

print("-" * 30)

##matrix multiplication
a = np.array([[1,4,8,6],[5,6,7,9]])
b = np.array([[5,8,10,12],[7,9,5,0]])
result = np.matmul(a, b.T)      ##(need transpose of b)
print(result)

print("-" * 30)

a = np.array([[1,4,8,6],[5,6,7,9]])
print(a)
b = np.array([[5,7],[8,9],[10,5],[12,0]])
print(b)
result = np.matmul(a, b)
print(result)

[[ 6 12 18 18]
 [12 15 12  9]]
[[ 5 32 80 72]
 [35 54 35  0]]
------------------------------
[[189  83]
 [251 124]]
------------------------------
[[1 4 8 6]
 [5 6 7 9]]
[[ 5  7]
 [ 8  9]
 [10  5]
 [12  0]]
[[189  83]
 [251 124]]


In [37]:
## Trigonometric functions
a = np.array([1,4,8,6])
print(np.sin(a))
print(np.cos(a))
print(np.tan(a))
print(1/np.cos(a))   ## secant (1/cos)

print(np.sec(a))  ##no direct secant function


[ 0.84147098 -0.7568025   0.98935825 -0.2794155 ]
[ 0.54030231 -0.65364362 -0.14550003  0.96017029]
[ 1.55740772  1.15782128 -6.79971146 -0.29100619]
[ 1.85081572 -1.52988566 -6.87285064  1.04148193]


AttributeError: module 'numpy' has no attribute 'sec'

In [45]:
##find the determinant
b = np.array([[5,7],[8,9]])
print(b)
print(np.linalg.det(b))

[[5 7]
 [8 9]]
-10.999999999999996


In [54]:
##Get inverse, eigenvalue
A = np.array([[4, 2],[1, 3]])
print(np.linalg.eig(A))
#or
eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

print(np.linalg.inv(A))


EigResult(eigenvalues=array([5., 2.]), eigenvectors=array([[ 0.89442719, -0.70710678],
       [ 0.4472136 ,  0.70710678]]))
Eigenvalues: [5. 2.]
Eigenvectors:
 [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]
[[ 0.3 -0.2]
 [-0.1  0.4]]


#### Statistics

In [55]:
stat = np.array([[1,2,4],[3,6,4],[5,9,10]])
print(stat)

[[ 1  2  4]
 [ 3  6  4]
 [ 5  9 10]]


In [58]:
print(np.max(stat))
print(np.max(stat, axis = 1))

10
[ 4  6 10]


In [59]:
print(np.min(stat))
print(np.min(stat, axis = 0))


1
[1 2 4]


In [60]:
print(np.mean(stat))
print(np.sum(stat))

4.888888888888889
44


In [61]:
print(np.var(stat))
print(np.std(stat))

8.098765432098766
2.8458329944145997


#### Reorganizing Array

In [67]:
before = np.array([[2,4,3,5],[5,8,5,8]])
print(before)

after = before.reshape(4,2)
print(after)

after = before.reshape(2,2,2)
print(after)

after = before.reshape(2,3)   ##there is a mismatch with orginal, will get an error
print(after)

[[2 4 3 5]
 [5 8 5 8]]
[[2 4]
 [3 5]
 [5 8]
 [5 8]]
[[[2 4]
  [3 5]]

 [[5 8]
  [5 8]]]


ValueError: cannot reshape array of size 8 into shape (2,3)

In [68]:
##Vertically stacking matrices
v1 = np.array([1,2,3,4])
v2 = np.array([15,18,24,35])

print(np.vstack([v2,v1]))
print(np.vstack([v2,v1,v2,v2]))

[[15 18 24 35]
 [ 1  2  3  4]]
[[15 18 24 35]
 [ 1  2  3  4]
 [15 18 24 35]
 [15 18 24 35]]


In [70]:
## Horizontal stacking matrices
h1 = np.array([1,2,3,4])
h2 = np.array([15,18])

print(np.hstack([h2,h1]))

h1 = np.array([1,2,3,4])
h2 = np.array([15,18,24,35])
print(np.hstack([h1,h2]))

[15 18  1  2  3  4]
[ 1  2  3  4 15 18 24 35]


#### Boolean and Indexing

In [90]:
file = np.array([[1,32,489,50,387,78,56,32,45,67,99,865,456],[3,6,98,35,4,345,678,23,567,89,45,67,45],[5,9,10,23,45,67,598,76,54,34,2,67,5]])
file

array([[  1,  32, 489,  50, 387,  78,  56,  32,  45,  67,  99, 865, 456],
       [  3,   6,  98,  35,   4, 345, 678,  23, 567,  89,  45,  67,  45],
       [  5,   9,  10,  23,  45,  67, 598,  76,  54,  34,   2,  67,   5]])

In [91]:
file > 45

array([[False, False,  True,  True,  True,  True,  True, False, False,
         True,  True,  True,  True],
       [False, False,  True, False, False,  True,  True, False,  True,
         True, False,  True, False],
       [False, False, False, False, False,  True,  True,  True,  True,
        False, False,  True, False]])

In [95]:
print(((file > 50 ) & (file < 100)))
print(((file > 50 ) and (file < 100)))  #With NumPy, you cannot use and directly for arrays; use bitwise operators &

[[False False False False False  True  True False False  True  True False
  False]
 [False False  True False False False False False False  True False  True
  False]
 [False False False False False  True False  True  True False False  True
  False]]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [97]:
(~((file > 50 ) & (file < 100)))  ##not greater than 50

array([[ True,  True,  True,  True,  True, False, False,  True,  True,
        False, False,  True,  True],
       [ True,  True, False,  True,  True,  True,  True,  True,  True,
        False,  True, False,  True],
       [ True,  True,  True,  True,  True, False,  True, False, False,
         True,  True, False,  True]])

In [85]:
file[file > 45]

array([489,  50, 387,  78,  56,  67,  99, 865, 456,  98, 345, 678, 567,
        89,  67,  67, 598,  76,  54,  67])

In [86]:
##want to see any of the data greater than 50 in columns or rows
print(np.any(file > 50 , axis = 0))

print(np.any(file > 50 , axis = 1))

[False False  True False  True  True  True  True  True  True  True  True
  True]
[ True  True  True]


In [87]:
file_data = np.array([1,32,489,50,387,78,56,32,45,67,99,865,456])
file_data[[10,4,6]]   ##want values of 10,4,6th index

array([ 99, 387,  56])

*Day 3 - Concatenation of arrays

In [11]:

import numpy as np 

x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
print(np.concatenate([x,y]))

grid = np.array([[1, 2, 3],
                 [4, 5, 6]])
print(np.concatenate([grid,grid]))
print(np.concatenate([grid,grid], axis = 0))
print(np.concatenate([grid,grid], axis = 1))

[1 2 3 3 2 1]
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


#### Reshaping of Arrays - without using reshape()

In [8]:
x = np.array([1, 2, 3])
print(x[np.newaxis , :])
print(x[: , np.newaxis])

[[1 2 3]]
[[1]
 [2]
 [3]]


#### Illustrate the concept of NumPy Broadcasting by providing examples that explain the broadcasting rules in different scenarios.

If two arrays have different dimensions, NumPy adds extra 1s to the smaller array’s shape (on the left side) so they can be compared or broadcast together.

In [18]:
array_1 = np.array([12,32,45,43])
array_2 =15
print(array_1 + array_2)

array_2 =15
array_1 = np.array([14,34,85,43])
result = array_1 + array_2
print(f"Broadcasting a scalar\n{array_2} + {array_1} = {result}")

[27 47 60 58]
Broadcasting a scalar
15 + [14 34 85 43] = [ 29  49 100  58]


If the shapes of two arrays differ in a dimension, and one of the arrays has size 1 in that dimension, NumPy stretches (repeats) that array along that dimension to match the other array.

In [28]:
array_1 = np.array([3,4,2,3])
array_2 = np.array([[10],[29],[39]])
print(np.ndim(array_1))
print(np.ndim(array_2))

result = array_1 + array_2
print(f"Broadcasting a 1D array to a 2D array : {array_1} + {array_2} = {result}")
print(f"Broadcasting a 1D array to a 2D array : \n{array_1}\n + \n{array_2}\n = \n{result}\n")

1
2
Broadcasting a 1D array to a 2D array : [3 4 2 3] + [[10]
 [29]
 [39]] = [[13 14 12 13]
 [32 33 31 32]
 [42 43 41 42]]
Broadcasting a 1D array to a 2D array : 
[3 4 2 3]
 + 
[[10]
 [29]
 [39]]
 = 
[[13 14 12 13]
 [32 33 31 32]
 [42 43 41 42]]



If in any dimension the sizes disagree and neither is equal to 1, an error is raised(Sizes must be equal or one of them must be 1 in that dimension for broadcasting.)

In [56]:
a = np.array([[1, 2],[1,3],[2,3]])      
b = np.array([[4,5,6],[3,5,2],[6,8,9]])         

result = a + b

ValueError: operands could not be broadcast together with shapes (3,2) (3,3) 

In [55]:
print(b[:, np.newaxis])

print("-" * 40)

print(a + b[:, np.newaxis])

print("-" * 40)

c = b[:, np.newaxis]
print(np.shape(c))
print(np.shape(a))

print("-" * 40)

print(a + b[np.newaxis , :])



[[4]
 [5]
 [6]]
----------------------------------------
[[5 6]
 [6 8]
 [8 9]]
----------------------------------------
(3, 1)
(3, 2)
----------------------------------------


ValueError: operands could not be broadcast together with shapes (3,2) (1,3) 

#### NumPy's Structured Arrays

NumPy's structured arrays and record arrays, which provide efficient storage for compound, heterogeneous data

In [18]:
name = ["John", "Kavin", "Leo Das", "Padma","Sree"]
marks = [89,78,45,27,69]
overall_percentage = [89.34, 77.99, 45.23, 26.55,68.99]

##There's nothing here that tells us that these arrays are related

In [3]:
# We use a compound data type for structured arrays
import numpy as np

data = np.zeros(5, dtype = {"names":("name","marks","overall_percentage"),
       "formats":("U10","i4","f8")})

name = ["John", "Kavin", "Leo Das", "Padma","Sree"]
marks = [89,78,45,27,69]
overall_percentage = [89.34, 77.99, 45.23, 26.55,68.99]

data["name"] = name
data["marks"] = marks
data["overall_percentage"] = overall_percentage
print(data)

##'U10' translates to "Unicode string of maximum length 10," 'i4' translates to "4-byte (i.e., 32 bit) integer," and 'f8' translates to "8-byte (i.e., 64 bit) float.

[('John', 89, 89.34) ('Kavin', 78, 77.99) ('Leo Das', 45, 45.23)
 ('Padma', 27, 26.55) ('Sree', 69, 68.99)]


In [4]:
##accessing the elements
print(data[1])
print(data[0])
print(data[3])

('Kavin', 78, 77.99)
('John', 89, 89.34)
('Padma', 27, 26.55)


In [6]:
## Using Boolean masking
print(data[data["marks"] < 30]["name"])
print(data[data["marks"] < 30])

['Padma']
[('Padma', 27, 26.55)]


In [22]:
## another way of creating a structured array
data = np.zeros(5, dtype = [("name","U10"),("marks","i4"),("overall_percentage","f8")])
name = ["John", "Kavin", "Leo Das", "Padma","Sree"]
marks = [45,69,89,27,78]
overall_percentage = [45.23,68.99,89.34,26.55,77.99]

data["name"] = name
data["marks"] = marks
data["overall_percentage"] = overall_percentage
print(data)

[('John', 45, 45.23) ('Kavin', 69, 68.99) ('Leo Das', 89, 89.34)
 ('Padma', 27, 26.55) ('Sree', 78, 77.99)]


In [17]:
data_rec = data.view(np.recarray)
print(data_rec.marks)
print(data_rec.name)


[45 69 89 27 78]
['John' 'Kavin' 'Leo Das' 'Padma' 'Sree']


In [26]:
## sort marks and show top 3 marks
sort = np.sort(data , order = "marks")
print(sort)

# To get the top 3
top3 = sort[::-1][:3]
print(top3)

[('Padma', 27, 26.55) ('John', 45, 45.23) ('Kavin', 69, 68.99)
 ('Sree', 78, 77.99) ('Leo Das', 89, 89.34)]
[('Leo Das', 89, 89.34) ('Sree', 78, 77.99) ('Kavin', 69, 68.99)]


In [32]:
## Intersection , union , symmetric difference
numA = np.array([1, 3, 5, 7, 9])
numB = np.array([2, 3, 5, 7, 11])

inte = np.intersect1d(numA, numB)
print(inte)

inte = np.union1d(numA, numB)
print(inte)

inte = np.setxor1d(numA, numB)
print(inte)

numA = np.array([[1, 3, 5, 7, 9],[2, 3, 5, 7, 11]])
numB = np.array([[2, 3, 5, 7, 11],[1, 3, 5, 7, 9]])

inte = np.intersect1d(numA, numB)
print(inte)

[3 5 7]
[ 1  2  3  5  7  9 11]
[ 1  2  9 11]
[ 1  2  3  5  7  9 11]
